In [8]:
import numpy as np
import pandas as pd

In [9]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [10]:
temperatures_w1.shape

(7,)

In [11]:
temperatures_w1.dtype

dtype('float64')

In [12]:
temperatures_w1.size

7

In [13]:
fahrenheit = (temperatures_w1 * 9/5) + 32

fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [14]:
np.max(temperatures_w1)

np.float64(26.1)

In [15]:
np.min(temperatures_w1)

np.float64(20.8)

In [16]:
np.mean(temperatures_w1)

np.float64(23.542857142857144)

In [17]:
temperatures_w1[:3]

array([22.5, 25.3, 20.8])

In [18]:
temperatures_w1[-2:]

array([24.8, 21.9])

In [19]:
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

In [20]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [21]:
temperatures.shape

(2, 7)

In [22]:
temperatures.dtype

dtype('float64')

In [23]:
temperatures.size

14

In [24]:
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [25]:
temperatures[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [26]:
temperatures[:, -2:]

array([[24.8, 21.9],
       [22.8, 20.1]])

In [27]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [29]:
marks.iloc[0]

np.int64(95)

In [30]:
marks.loc[['Rank1', 'Rank2', 'Rank3']]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [31]:
marks.iloc[2]

np.int64(89)

In [32]:
marks[marks > 90]

Rank1    95
Rank2    92
dtype: int64

In [33]:
marks['Rank1'] = 100

marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [34]:
marks = marks.drop('Rank5')

marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [35]:
cgpa = marks / 10

cgpa

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [36]:
transactions = pd.DataFrame({
    'TransactionID':[101,102,103,104,105,106,107,108,109,110],
    'ProductCategory':['Electronics','Clothing','Electronics',
                       'Furniture','Clothing','Electronics',
                       'Furniture','Clothing','Furniture',
                       'Electronics'],
    'Region':['North','South','North','East','West',
              'North','East','West','South','North'],
    'Amount':[200,150,300,450,200,250,300,180,350,400]
})

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [37]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [38]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [39]:
transactions.shape

(10, 4)

In [40]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [41]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [42]:
transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [43]:
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [44]:
transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [45]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [46]:
transactions['Region'].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [47]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [48]:
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [49]:
transactions['Discount'] = transactions['Amount'] * 0.10

transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [50]:
transactions = transactions[
    transactions['TransactionID'] != 109
]

transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [51]:
transactions.drop('Discount', axis=1, inplace=True)

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400